### ISSUE TITLE
TYSM

### ISSUE THREAD

**Issue by ZenaMel** [LayZeeDK/github-pages-docusaurus#1]
Thanks a lot for this. I was banging my head against the wall trying to get Pages working with the legacy workflow and weird stuff was happening like it showing the readme file etc.

The workflow and instructions combined worked _instantly_. You made my day.

**Comment by LayZeeDK** [comment]
Thank you, @Zenahr 🙇‍♂️

**Comment by boltex** [comment]
Thank you @LayZeeDK  for setting this up! 

Like @Zenahr, I also looked at your config setup to help get my own github project docum hosting up and running ! 😄

**Comment by LayZeeDK** [comment]
Glad to hear that it's still working for you, @boltex
